export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const USE_PRODUCT = 'USE_PRODUCT;'
export const UPDATE_TIME = 'UPDATE_TIME';
export const REQUEST_RECIPES='REQUEST_RECIPES'
export const GET_RECIPES_FAILURE='GET_RECIPES_FAILURE'
export const GET_RECIPES_SUCCESS='GET_RECIPES_SUCCESS'